### ISSUE TITLE
First step. React from tutorial [Main task]

### ISSUE THREAD

**Issue by atherdon** [GroceriStar/react-intern-only-27#1]
https://medium.com/quick-code/lets-learn-react-chapter-1-setting-up-environment-e9505b6644

after reading each chapter you need to push your code updates here and also give me a short resume about what exactly did you. it'll needed for better understanding your progress

**Comment by xFloki** [comment]
Hello @atherdon 
Seems like a I don't have write access on this repo.

**Comment by atherdon** [comment]
hold on


On 07-Jul-2018 at 04:33 PM, Alejandro Dietta wrote:


Hello @atherdon <https://github.com/atherdon>
Seems like a I don't have write access on this repo.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/GroceriStar/react-intern-only-27/issues/1#issuecomment-403227320>,
or mute the thread

**Comment by atherdon** [comment]
https://github.com/GroceriStar/react-intern-only-27/invitations
